# Generated by Django 4.0.3 on 2022-05-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0002_user_hits_user_turns_match_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Winner', 'Winner'), ('Loser', 'Loser'), ('Unknown', 'Unknown')], max_length=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_2',
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='battleship.PlayerInGame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleship.match'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
