# Generated by Django 4.0.3 on 2022-05-23 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0008_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='battleship.PlayerInGame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='type',
            field=models.CharField(choices=[('Winner', 'Winner'), ('Loser', 'Loser'), ('Unknown', 'Unknown')], default='UKNOWN', max_length=7),
        ),
    ]
