# Generated by Django 4.0.3 on 2022-05-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0010_alter_match_winner_alter_playeringame_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeringame',
            options={'verbose_name_plural': 'InGame Players'},
        ),
    ]
