# Generated by Django 4.0.3 on 2022-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0011_alter_playeringame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='type',
            field=models.CharField(choices=[('Winner', 'Winner'), ('Loser', 'Loser'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
    ]
