# Generated by Django 4.0.3 on 2022-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0012_alter_playeringame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='map',
            field=models.CharField(default='[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]', max_length=41),
        ),
    ]
