# Generated by Django 4.0.3 on 2022-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0013_playeringame_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='inGameMap',
            field=models.CharField(blank=True, default='[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]', max_length=41),
        ),
    ]
