# Generated by Django 4.0.3 on 2022-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0014_playeringame_ingamemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='inGameMap',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='map',
            field=models.CharField(default='[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]', max_length=56),
        ),
    ]
