# Generated by Django 4.0.3 on 2022-05-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0015_alter_playeringame_ingamemap_alter_playeringame_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='map',
            field=models.CharField(default='[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]', max_length=56),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
