# Generated by Django 4.0.1 on 2022-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
