# Generated by Django 4.0.1 on 2022-03-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='media/')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
