# Generated by Django 4.0.3 on 2022-05-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('json_file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
