# Generated by Django 4.0.3 on 2022-05-03 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipient_file_delete_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient_file',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'xlsx', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='recipient_file',
            name='json_file',
            field=models.FileField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
