# Generated by Django 4.0.3 on 2022-05-03 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipient_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient_file',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
