# Generated by Django 4.0.1 on 2022-02-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
