# Generated by Django 4.0.1 on 2022-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1000)),
                ('bid', models.IntegerField()),
                ('user', models.CharField(max_length=24)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
