# Generated by Django 4.0.1 on 2022-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=64)),
                ('listings', models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing')),
            ],
        ),
    ]
