# Generated by Django 4.0.4 on 2022-04-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_user_test_watchlist_listing_seller_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_on', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
