# Generated by Django 4.0.4 on 2022-04-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_base_price_alter_listing_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categories',
        ),
    ]
