# Generated by Django 4.0.1 on 2022-02-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_categories_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('bid', models.IntegerField()),
                ('listing_title', models.CharField(max_length=100)),
            ],
        ),
    ]
