# Generated by Django 4.0.4 on 2022-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_category_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='base_price',
            field=models.IntegerField(blank=True),
        ),
    ]
