# Generated by Django 4.0.4 on 2022-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='base_price',
            field=models.IntegerField(),
        ),
    ]
