# Generated by Django 4.0.3 on 2022-04-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
