# Generated by Django 4.0.3 on 2022-04-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_wathclist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wathclist',
            new_name='Watchlist',
        ),
    ]
